In [56]:
#importing 
from matplotlib import pyplot as plt
from scipy.stats import linregress
import numpy as np
from sklearn import datasets
import pandas as pd

In [57]:
#Import Physcial Activity 
PA_csv_path = "Physical_Activity.csv"
initial_data = pd.read_csv(PA_csv_path)
del initial_data['Difference in male sufficient physical activity prevalence, 2001-2009 (percentage points)']
del initial_data['Difference in female sufficient physical activity prevalence, 2001-2009 (percentage points)']
initial_data.head()

,State,County,"Male sufficient physical activity prevalence, 2001 (%)","Female sufficient physical activity prevalence, 2001 (%)","Male sufficient physical activity prevalence, 2009 (%)","Female sufficient physical activity prevalence, 2009 (%)","Male sufficient physical activity prevalence, 2011* (%)","Female sufficient physical activity prevalence, 2011* (%)",Unnamed: 10,*Methodological changes in the 2011 BRFSS may affect comparability between the 2011 estimates and estimates from earlier years
0,United States,NaN,56.8,46.7,57.8,51.3,56.3,52.6,NaN,NaN
1,Alabama,NaN,52.4,40.4,51.5,41.4,49.5,42.0,NaN,NaN
2,Alabama,Autauga,55.0,43.6,55.1,46.8,52.9,47.5,NaN,NaN
3,Alabama,Baldwin,55.4,48.4,56.6,49.2,54.1,49.6,NaN,NaN
4,Alabama,Barbour,45.7,33.0,46.4,34.6,44.9,35.8,NaN,NaN

In [61]:
#Import Physcial Activity 
Obesity_csv_path = "Obesity.csv"
Obesity_initial_data = pd.read_csv(Obesity_csv_path)

Obesity_initial_data.head()

,State,County,"Male obesity prevalence, 2001 (%)","Female obesity prevalence, 2001 (%)","Male obesity prevalence, 2009 (%)","Female obesity prevalence, 2009 (%)","Male obesity prevalence, 2011* (%)","Female obesity prevalence, 2011* (%)","Difference in male obesity prevalence, 2001-2009 (percentage points)","Difference in female obesity prevalence, 2001-2009 (percentage points)",Unnamed: 10,*Methodological changes in the 2011 BRFSS may affect comparability between the 2011 estimates and estimates from earlier years
0,United States,NaN,26.1,28.7,32.8,35.1,33.8,36.1,6.7,6.4,NaN,NaN
1,Alabama,NaN,29.7,34.1,36.1,41.2,37.3,42.2,6.4,7.1,NaN,NaN
2,Alabama,Autauga,30.7,32.3,35.9,37.4,37.1,38.8,5.3,5.2,NaN,NaN
3,Alabama,Baldwin,27.8,28.3,32.4,33.0,33.5,33.9,4.5,4.6,NaN,NaN
4,Alabama,Barbour,32.3,42.8,40.3,51.3,41.5,51.6,8.0,8.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3189,Wyoming,Sweetwater,26.6,26.1,33.6,35.3,34.7,36.0,7.0,9.2,NaN,NaN
3190,Wyoming,Teton,17.8,16.6,21.1,18.8,21.6,19.6,3.2,2.3,NaN,NaN
3191,Wyoming,Uinta,24.1,25.0,35.2,34.0,36.5,34.8,11.1,9.0,NaN,NaN
3192,Wyoming,Washakie,23.5,24.9,31.3,33.9,32.4,34.7,7.7,9.0,NaN,NaN
3193,Wyoming,Weston,27.0,28.4,35.7,35.0,36.8,35.9,8.7,6.5,NaN,NaN

In [59]:
# Merge  two datasets on "State" so that no data is lost 
combined_PA_Obesity_df = pd.merge(initial_data, Obesity_initial_data,
                                 how='left', on='State')
combined_PA_Obesity_df.head()

,State,County_x,"Male sufficient physical activity prevalence, 2001 (%)","Female sufficient physical activity prevalence, 2001 (%)","Male sufficient physical activity prevalence, 2009 (%)","Female sufficient physical activity prevalence, 2009 (%)","Male sufficient physical activity prevalence, 2011* (%)","Female sufficient physical activity prevalence, 2011* (%)",Unnamed: 10_x,*Methodological changes in the 2011 BRFSS may affect comparability between the 2011 estimates and estimates from earlier years_x,...,"Male obesity prevalence, 2001 (%)","Female obesity prevalence, 2001 (%)","Male obesity prevalence, 2009 (%)","Female obesity prevalence, 2009 (%)","Male obesity prevalence, 2011* (%)","Female obesity prevalence, 2011* (%)","Difference in male obesity prevalence, 2001-2009 (percentage points)","Difference in female obesity prevalence, 2001-2009 (percentage points)",Unnamed: 10_y,*Methodological changes in the 2011 BRFSS may affect comparability between the 2011 estimates and estimates from earlier years_y
0,United States,NaN,56.8,46.7,57.8,51.3,56.3,52.6,NaN,NaN,...,26.1,28.7,32.8,35.1,33.8,36.1,6.7,6.4,NaN,NaN
1,Alabama,NaN,52.4,40.4,51.5,41.4,49.5,42.0,NaN,NaN,...,29.7,34.1,36.1,41.2,37.3,42.2,6.4,7.1,NaN,NaN
2,Alabama,NaN,52.4,40.4,51.5,41.4,49.5,42.0,NaN,NaN,...,30.7,32.3,35.9,37.4,37.1,38.8,5.3,5.2,NaN,NaN
3,Alabama,NaN,52.4,40.4,51.5,41.4,49.5,42.0,NaN,NaN,...,27.8,28.3,32.4,33.0,33.5,33.9,4.5,4.6,NaN,NaN
4,Alabama,NaN,52.4,40.4,51.5,41.4,49.5,42.0,NaN,NaN,...,32.3,42.8,40.3,51.3,41.5,51.6,8.0,8.5,NaN,NaN

In [60]:
#clean columns
del combined_PA_Obesity_df["County_x"]
del combined_PA_Obesity_df["County_y"]
del combined_PA_Obesity_df["Unnamed: 10_x"]
del combined_PA_Obesity_df["Unnamed: 10_y"]
del combined_PA_Obesity_df['*Methodological changes in the 2011 BRFSS may affect comparability between the 2011 estimates and estimates from earlier years_x']
del combined_PA_Obesity_df['*Methodological changes in the 2011 BRFSS may affect comparability between the 2011 estimates and estimates from earlier years_y']
combined_PA_Obesity_df.head()

,State,"Male sufficient physical activity prevalence, 2001 (%)","Female sufficient physical activity prevalence, 2001 (%)","Male sufficient physical activity prevalence, 2009 (%)","Female sufficient physical activity prevalence, 2009 (%)","Male sufficient physical activity prevalence, 2011* (%)","Female sufficient physical activity prevalence, 2011* (%)","Male obesity prevalence, 2001 (%)","Female obesity prevalence, 2001 (%)","Male obesity prevalence, 2009 (%)","Female obesity prevalence, 2009 (%)","Male obesity prevalence, 2011* (%)","Female obesity prevalence, 2011* (%)","Difference in male obesity prevalence, 2001-2009 (percentage points)","Difference in female obesity prevalence, 2001-2009 (percentage points)"
0,United States,56.8,46.7,57.8,51.3,56.3,52.6,26.1,28.7,32.8,35.1,33.8,36.1,6.7,6.4
1,Alabama,52.4,40.4,51.5,41.4,49.5,42.0,29.7,34.1,36.1,41.2,37.3,42.2,6.4,7.1
2,Alabama,52.4,40.4,51.5,41.4,49.5,42.0,30.7,32.3,35.9,37.4,37.1,38.8,5.3,5.2
3,Alabama,52.4,40.4,51.5,41.4,49.5,42.0,27.8,28.3,32.4,33.0,33.5,33.9,4.5,4.6
4,Alabama,52.4,40.4,51.5,41.4,49.5,42.0,32.3,42.8,40.3,51.3,41.5,51.6,8.0,8.5

In [ ]:
# This example compares different factors in the Boston housing data set
boston_data = datasets.load_boston()
housing_data = pd.DataFrame(data=boston_data.data,columns=boston_data.feature_names)
housing_data['MEDV'] = boston_data.target

# This example compares different factors in the obesity andn physical activity data set
comined_PA_Obesity = datasets.load_(male)
data = pd.DataFrame(data=boston_data.data,columns=boston_data.feature_names)
housing_data['MEDV'] = boston_data.target

In [ ]:
# Plot out rooms versus median house price
x_values = housing_data['RM']
y_values = housing_data['MEDV']
plt.scatter(x_values,y_values)
plt.xlabel('Rooms in House')
plt.ylabel('Median House Prices ($1000)')
plt.show()

In [ ]:
# Add the linear regression equation and line to plot
x_values = housing_data['RM']
y_values = housing_data['MEDV']
(slope, intercept, rvalue, pvalue, stderr) = linregress(x_values, y_values)
regress_values = x_values * slope + intercept
line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))
plt.scatter(x_values,y_values)
plt.plot(x_values,regress_values,"r-")
plt.annotate(line_eq,(6,10),fontsize=15,color="red")
plt.xlabel('Rooms in House')
plt.ylabel('Median House Prices ($1000)')
plt.show()

In [ ]:
# Print out the r-squared value along with the plot.
x_values = housing_data['RM']
y_values = housing_data['MEDV']
(slope, intercept, rvalue, pvalue, stderr) = linregress(x_values, y_values)
regress_values = x_values * slope + intercept
line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))
plt.scatter(x_values,y_values)
plt.plot(x_values,regress_values,"r-")
plt.annotate(line_eq,(6,10),fontsize=15,color="red")
plt.xlabel('Rooms in House')
plt.ylabel('Median House Prices ($1000)')
print(f"The r-squared is: {rvalue**2}")
plt.show()

In [ ]:
# The next example looks at a diabetes data set with less linear relationships
diabetes_data = datasets.load_diabetes()
data = pd.DataFrame(diabetes_data.data,columns=diabetes_data.feature_names)
data['1Y_Disease_Progress'] = diabetes_data.target

In [ ]:
x_values = data['bp']
y_values = data['1Y_Disease_Progress']
(slope, intercept, rvalue, pvalue, stderr) = linregress(x_values, y_values)
regress_values = x_values * slope + intercept
line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))
plt.scatter(x_values,y_values)
plt.plot(x_values,regress_values,"r-")
plt.annotate(line_eq,(0,50),fontsize=15,color="red")
plt.xlabel('Normalized Blood Pressure')
plt.ylabel('1Y_Disease_Progress')
print(f"The r-squared is: {rvalue**2}")
plt.show()